INSERT INTO localidad (id_localidad,nombre) values ('14','Achiras');
INSERT INTO localidad (id_localidad,nombre) values ('15','Adelia María');
INSERT INTO localidad (id_localidad,nombre) values ('16','Agua de Oro');
INSERT INTO localidad (id_localidad,nombre) values ('17','Alcira (Gigena)');
INSERT INTO localidad (id_localidad,nombre) values ('18','Aldea Santa María');
INSERT INTO localidad (id_localidad,nombre) values ('19','Alejandro Roca (Est. Alejandro)');
INSERT INTO localidad (id_localidad,nombre) values ('20','Alejo Ledesma');
INSERT INTO localidad (id_localidad,nombre) values ('21','Alicia');
INSERT INTO localidad (id_localidad,nombre) values ('22','Almafuerte');
INSERT INTO localidad (id_localidad,nombre) values ('23','Alpa Corral');
INSERT INTO localidad (id_localidad,nombre) values ('24','Alta Gracia');
INSERT INTO localidad (id_localidad,nombre) values ('25','Alto Alegre');
INSERT INTO localidad (id_localidad,nombre) values ('26','Alto de los Quebrachos');
INSERT INTO localidad (id_localidad,nombre) values ('27','Altos de Chipión');
INSERT INTO localidad (id_localidad,nombre) values ('28','Amboy');
INSERT INTO localidad (id_localidad,nombre) values ('29','Ámbul');
INSERT INTO localidad (id_localidad,nombre) values ('30','Ana Zumarán');
INSERT INTO localidad (id_localidad,nombre) values ('31','Anisacate');
INSERT INTO localidad (id_localidad,nombre) values ('32','Arias');
INSERT INTO localidad (id_localidad,nombre) values ('33','Arroyito');
INSERT INTO localidad (id_localidad,nombre) values ('34','Arroyo Algodón');
INSERT INTO localidad (id_localidad,nombre) values ('35','Arroyo Cabral');
INSERT INTO localidad (id_localidad,nombre) values ('36','Arroyo Los Patos');
INSERT INTO localidad (id_localidad,nombre) values ('37','Ascochinga');
INSERT INTO localidad (id_localidad,nombre) values ('38','Assunta');
INSERT INTO localidad (id_localidad,nombre) values ('39','Atahona');
INSERT INTO localidad (id_localidad,nombre) values ('40','Ausonia');
INSERT INTO localidad (id_localidad,nombre) values ('41','Avellaneda');
INSERT INTO localidad (id_localidad,nombre) values ('42','Ballesteros');
INSERT INTO localidad (id_localidad,nombre) values ('43','Ballesteros Sur');
INSERT INTO localidad (id_localidad,nombre) values ('44','Balnearia');
INSERT INTO localidad (id_localidad,nombre) values ('45','Bañado de Soto');
INSERT INTO localidad (id_localidad,nombre) values ('46','Barrio Gilbert ((1° de Mayo) - Tejas Tres)');
INSERT INTO localidad (id_localidad,nombre) values ('47','Barrio Nuevo Rio Ceballos');
INSERT INTO localidad (id_localidad,nombre) values ('48','Barrio Santa Isabel');
INSERT INTO localidad (id_localidad,nombre) values ('49','Bell Ville');
INSERT INTO localidad (id_localidad,nombre) values ('50','Bengolea');
INSERT INTO localidad (id_localidad,nombre) values ('51','Benjamín Gould');
INSERT INTO localidad (id_localidad,nombre) values ('52','Berrotarán');
INSERT INTO localidad (id_localidad,nombre) values ('53','Bialet Massé');
INSERT INTO localidad (id_localidad,nombre) values ('54','Bouwer');
INSERT INTO localidad (id_localidad,nombre) values ('55','Brinkmann');
INSERT INTO localidad (id_localidad,nombre) values ('56','Bulnes');
INSERT INTO localidad (id_localidad,nombre) values ('57','Cabalango');
INSERT INTO localidad (id_localidad,nombre) values ('58','Calchín');
INSERT INTO localidad (id_localidad,nombre) values ('59','Calchín Oeste');
INSERT INTO localidad (id_localidad,nombre) values ('60','Camilo Aldao');
INSERT INTO localidad (id_localidad,nombre) values ('61','Caminiaga');
INSERT INTO localidad (id_localidad,nombre) values ('62','Campos del Virrey');
INSERT INTO localidad (id_localidad,nombre) values ('63','Cañada del Sauce');
INSERT INTO localidad (id_localidad,nombre) values ('64','Cañada de Luque');
INSERT INTO localidad (id_localidad,nombre) values ('65','Cañada de Machado');
INSERT INTO localidad (id_localidad,nombre) values ('66','Cañada de Río Pinto');
INSERT INTO localidad (id_localidad,nombre) values ('67','Canals');
INSERT INTO localidad (id_localidad,nombre) values ('68','Candelaria Sur');
INSERT INTO localidad (id_localidad,nombre) values ('69','Canteras El Sauce');
INSERT INTO localidad (id_localidad,nombre) values ('70','Canteras Quilpo');
INSERT INTO localidad (id_localidad,nombre) values ('71','Capilla del Carmen');
INSERT INTO localidad (id_localidad,nombre) values ('72','Capilla del Monte');
INSERT INTO localidad (id_localidad,nombre) values ('73','Capilla de los Remedios');
INSERT INTO localidad (id_localidad,nombre) values ('74','Capilla de Sitón');
INSERT INTO localidad (id_localidad,nombre) values ('75','Capilla Vieja');
INSERT INTO localidad (id_localidad,nombre) values ('76','Capitán General Bernardo OHiggins');
INSERT INTO localidad (id_localidad,nombre) values ('77','Carnerillo');
INSERT INTO localidad (id_localidad,nombre) values ('78','Carrilobo');
INSERT INTO localidad (id_localidad,nombre) values ('79','Casa Bamba');
INSERT INTO localidad (id_localidad,nombre) values ('80','Casa Grande');
INSERT INTO localidad (id_localidad,nombre) values ('81','Caseros Centro');
INSERT INTO localidad (id_localidad,nombre) values ('82','Causana');
INSERT INTO localidad (id_localidad,nombre) values ('83','Cavanagh');
INSERT INTO localidad (id_localidad,nombre) values ('84','Cerro Colorado');
INSERT INTO localidad (id_localidad,nombre) values ('85','Chaján');
INSERT INTO localidad (id_localidad,nombre) values ('86','Chalacea');
INSERT INTO localidad (id_localidad,nombre) values ('87','Chañar Viejo');
INSERT INTO localidad (id_localidad,nombre) values ('88','Chancaní');
INSERT INTO localidad (id_localidad,nombre) values ('89','Charbonier');
INSERT INTO localidad (id_localidad,nombre) values ('90','Charras');
INSERT INTO localidad (id_localidad,nombre) values ('91','Chazón');
INSERT INTO localidad (id_localidad,nombre) values ('92','Chilibroste');
INSERT INTO localidad (id_localidad,nombre) values ('93','Chucul');
INSERT INTO localidad (id_localidad,nombre) values ('94','Chuña');
INSERT INTO localidad (id_localidad,nombre) values ('95','Chuña Huasi');
INSERT INTO localidad (id_localidad,nombre) values ('96','Churqui Cañada');
INSERT INTO localidad (id_localidad,nombre) values ('97','Ciénaga del Coro');
INSERT INTO localidad (id_localidad,nombre) values ('98','Cintra');
INSERT INTO localidad (id_localidad,nombre) values ('99','Colazo');
INSERT INTO localidad (id_localidad,nombre) values ('100','Colonia 10 de Julio');
INSERT INTO localidad (id_localidad,nombre) values ('101','Colonia Almada');
INSERT INTO localidad (id_localidad,nombre) values ('102','Colonia Anita');
INSERT INTO localidad (id_localidad,nombre) values ('103','Colonia Barge');
INSERT INTO localidad (id_localidad,nombre) values ('104','Colonia Bismarck');
INSERT INTO localidad (id_localidad,nombre) values ('105','Colonia Bremen');
INSERT INTO localidad (id_localidad,nombre) values ('106','Colonia Caroya');
INSERT INTO localidad (id_localidad,nombre) values ('107','Colonia Italiana');
INSERT INTO localidad (id_localidad,nombre) values ('108','Colonia Iturraspe');
INSERT INTO localidad (id_localidad,nombre) values ('109','Colonia Las Cuatro Esquinas');
INSERT INTO localidad (id_localidad,nombre) values ('110','Colonia Las Pichanas');
INSERT INTO localidad (id_localidad,nombre) values ('111','Colonia Marina');
INSERT INTO localidad (id_localidad,nombre) values ('112','Colonia Prosperidad');
INSERT INTO localidad (id_localidad,nombre) values ('113','Colonia San Bartolomé');
INSERT INTO localidad (id_localidad,nombre) values ('114','Colonia San Pedro');
INSERT INTO localidad (id_localidad,nombre) values ('115','Colonia Santa María');
INSERT INTO localidad (id_localidad,nombre) values ('116','Colonia Tirolesa');
INSERT INTO localidad (id_localidad,nombre) values ('117','Colonia Valtelina');
INSERT INTO localidad (id_localidad,nombre) values ('118','Colonia Veinticinco');
INSERT INTO localidad (id_localidad,nombre) values ('119','Colonia Vicente Agüero');
INSERT INTO localidad (id_localidad,nombre) values ('120','Colonia Videla');
INSERT INTO localidad (id_localidad,nombre) values ('121','Colonia Vignaud');
INSERT INTO localidad (id_localidad,nombre) values ('122','Conlara');
INSERT INTO localidad (id_localidad,nombre) values ('123','Copacabana');
INSERT INTO localidad (id_localidad,nombre) values ('124','Córdoba');
INSERT INTO localidad (id_localidad,nombre) values ('125','Coronel Baigorria');
INSERT INTO localidad (id_localidad,nombre) values ('126','Coronel Moldes');
INSERT INTO localidad (id_localidad,nombre) values ('127','Corral de Bustos');
INSERT INTO localidad (id_localidad,nombre) values ('128','Corralito');
INSERT INTO localidad (id_localidad,nombre) values ('129','Corral Quemado');
INSERT INTO localidad (id_localidad,nombre) values ('130','Cosquín');
INSERT INTO localidad (id_localidad,nombre) values ('131','Costa Azul');
INSERT INTO localidad (id_localidad,nombre) values ('132','Costa Sacate');
INSERT INTO localidad (id_localidad,nombre) values ('133','Country Chacras de la Villa ( - Country San Isidro)');
INSERT INTO localidad (id_localidad,nombre) values ('134','Cruz Alta');
INSERT INTO localidad (id_localidad,nombre) values ('135','Cruz Caña');
INSERT INTO localidad (id_localidad,nombre) values ('136','Cruz de Caña');
INSERT INTO localidad (id_localidad,nombre) values ('137','Cruz del Eje');
INSERT INTO localidad (id_localidad,nombre) values ('138','Cuesta Blanca');
INSERT INTO localidad (id_localidad,nombre) values ('139','Dalmacio Vélez');
INSERT INTO localidad (id_localidad,nombre) values ('140','Deán Funes');
INSERT INTO localidad (id_localidad,nombre) values ('141','Del Campillo');
INSERT INTO localidad (id_localidad,nombre) values ('142','Despeñaderos');
INSERT INTO localidad (id_localidad,nombre) values ('143','Devoto');
INSERT INTO localidad (id_localidad,nombre) values ('144','Diego de Rojas');
INSERT INTO localidad (id_localidad,nombre) values ('145','Dique Chico');
INSERT INTO localidad (id_localidad,nombre) values ('146','Dos Arroyos');
INSERT INTO localidad (id_localidad,nombre) values ('147','El Alcalde (Est. Tala Norte)');
INSERT INTO localidad (id_localidad,nombre) values ('148','El Arañado');
INSERT INTO localidad (id_localidad,nombre) values ('149','El Brete');
INSERT INTO localidad (id_localidad,nombre) values ('150','El Chacho');
INSERT INTO localidad (id_localidad,nombre) values ('151','El Corcovado - El Torreón');
INSERT INTO localidad (id_localidad,nombre) values ('152','El Crispín');
INSERT INTO localidad (id_localidad,nombre) values ('153','El Durazno');
INSERT INTO localidad (id_localidad,nombre) values ('154','Elena');
INSERT INTO localidad (id_localidad,nombre) values ('155','El Fortín');
INSERT INTO localidad (id_localidad,nombre) values ('156','El Fuertecito');
INSERT INTO localidad (id_localidad,nombre) values ('157','El Huayco');
INSERT INTO localidad (id_localidad,nombre) values ('158','El Manzano');
INSERT INTO localidad (id_localidad,nombre) values ('159','El Pantanillo');
INSERT INTO localidad (id_localidad,nombre) values ('160','El Potrerillo');
INSERT INTO localidad (id_localidad,nombre) values ('161','El Rastreador');
INSERT INTO localidad (id_localidad,nombre) values ('162','El Rincón');
INSERT INTO localidad (id_localidad,nombre) values ('163','El Rodeo');
INSERT INTO localidad (id_localidad,nombre) values ('164','El Tío');
INSERT INTO localidad (id_localidad,nombre) values ('165','El Tuscal');
INSERT INTO localidad (id_localidad,nombre) values ('166','Embalse');
INSERT INTO localidad (id_localidad,nombre) values ('167','Esquina');
INSERT INTO localidad (id_localidad,nombre) values ('168','Esquina del Alambre');
INSERT INTO localidad (id_localidad,nombre) values ('169','Estación Colonia Tirolesa');
INSERT INTO localidad (id_localidad,nombre) values ('170','Estación Lecueder');
INSERT INTO localidad (id_localidad,nombre) values ('171','Estación Luxardo');
INSERT INTO localidad (id_localidad,nombre) values ('172','Estancia de Guadalupe');
INSERT INTO localidad (id_localidad,nombre) values ('173','Estancia Vieja');
INSERT INTO localidad (id_localidad,nombre) values ('174','Etruria');
INSERT INTO localidad (id_localidad,nombre) values ('175','Eufrasio Loza');
INSERT INTO localidad (id_localidad,nombre) values ('176','Falda del Cañete');
INSERT INTO localidad (id_localidad,nombre) values ('177','Falda del Carmen');
INSERT INTO localidad (id_localidad,nombre) values ('178','Freyre');
INSERT INTO localidad (id_localidad,nombre) values ('179','General Baldissera');
INSERT INTO localidad (id_localidad,nombre) values ('180','General Cabrera');
INSERT INTO localidad (id_localidad,nombre) values ('181','General Deheza');
INSERT INTO localidad (id_localidad,nombre) values ('182','General Fotheringham');
INSERT INTO localidad (id_localidad,nombre) values ('183','General Levalle');
INSERT INTO localidad (id_localidad,nombre) values ('184','General Paz');
INSERT INTO localidad (id_localidad,nombre) values ('185','General Roca');
INSERT INTO localidad (id_localidad,nombre) values ('186','Guanaco Muerto');
INSERT INTO localidad (id_localidad,nombre) values ('187','Guasapampa');
INSERT INTO localidad (id_localidad,nombre) values ('188','Guatimozín');
INSERT INTO localidad (id_localidad,nombre) values ('189','Gutemberg');
INSERT INTO localidad (id_localidad,nombre) values ('190','Hernando');
INSERT INTO localidad (id_localidad,nombre) values ('191','Hipólito Bouchard');
INSERT INTO localidad (id_localidad,nombre) values ('192','Huanchillas');
INSERT INTO localidad (id_localidad,nombre) values ('193','Huerta Grande');
INSERT INTO localidad (id_localidad,nombre) values ('194','Huinca Renancó');
INSERT INTO localidad (id_localidad,nombre) values ('195','Idiazábal');
INSERT INTO localidad (id_localidad,nombre) values ('196','Impira');
INSERT INTO localidad (id_localidad,nombre) values ('197','Inriville');
INSERT INTO localidad (id_localidad,nombre) values ('198','Isla Verde');
INSERT INTO localidad (id_localidad,nombre) values ('199','Italó');
INSERT INTO localidad (id_localidad,nombre) values ('200','James Craik');
INSERT INTO localidad (id_localidad,nombre) values ('201','Jesús María');
INSERT INTO localidad (id_localidad,nombre) values ('202','José de la Quintana');
INSERT INTO localidad (id_localidad,nombre) values ('203','Justiniano Posse');
INSERT INTO localidad (id_localidad,nombre) values ('204','Kilómetro 658');
INSERT INTO localidad (id_localidad,nombre) values ('205','La Banda');
INSERT INTO localidad (id_localidad,nombre) values ('206','La Batea');
INSERT INTO localidad (id_localidad,nombre) values ('207','La Boca del Río');
INSERT INTO localidad (id_localidad,nombre) values ('208','Laborde');
INSERT INTO localidad (id_localidad,nombre) values ('209','Laboulaye');
INSERT INTO localidad (id_localidad,nombre) values ('210','La Calera');
INSERT INTO localidad (id_localidad,nombre) values ('211','La Carbonada');
INSERT INTO localidad (id_localidad,nombre) values ('212','La Carlota');
INSERT INTO localidad (id_localidad,nombre) values ('213','La Carolina');
INSERT INTO localidad (id_localidad,nombre) values ('214','La Cautiva');
INSERT INTO localidad (id_localidad,nombre) values ('215','La Cesira');
INSERT INTO localidad (id_localidad,nombre) values ('216','La Cortadera');
INSERT INTO localidad (id_localidad,nombre) values ('217','La Cruz');
INSERT INTO localidad (id_localidad,nombre) values ('218','La Cumbre');
INSERT INTO localidad (id_localidad,nombre) values ('219','La Cumbrecita');
INSERT INTO localidad (id_localidad,nombre) values ('220','La Falda');
INSERT INTO localidad (id_localidad,nombre) values ('221','La Francia');
INSERT INTO localidad (id_localidad,nombre) values ('222','La Gilda');
INSERT INTO localidad (id_localidad,nombre) values ('223','La Granja');
INSERT INTO localidad (id_localidad,nombre) values ('224','Laguna Larga');
INSERT INTO localidad (id_localidad,nombre) values ('225','La Higuera');
INSERT INTO localidad (id_localidad,nombre) values ('226','La Laguna');
INSERT INTO localidad (id_localidad,nombre) values ('227','La Morada');
INSERT INTO localidad (id_localidad,nombre) values ('228','La Paisanita');
INSERT INTO localidad (id_localidad,nombre) values ('229','La Palestina');
INSERT INTO localidad (id_localidad,nombre) values ('230','La Pampa');
INSERT INTO localidad (id_localidad,nombre) values ('231','La Paquita');
INSERT INTO localidad (id_localidad,nombre) values ('232','La Para');
INSERT INTO localidad (id_localidad,nombre) values ('233','La Paz');
INSERT INTO localidad (id_localidad,nombre) values ('234','La Perla');
INSERT INTO localidad (id_localidad,nombre) values ('235','La Playa');
INSERT INTO localidad (id_localidad,nombre) values ('236','La Playosa');
INSERT INTO localidad (id_localidad,nombre) values ('237','La Población');
INSERT INTO localidad (id_localidad,nombre) values ('238','La Posta');
INSERT INTO localidad (id_localidad,nombre) values ('239','La Puerta');
INSERT INTO localidad (id_localidad,nombre) values ('240','La Puerta');
INSERT INTO localidad (id_localidad,nombre) values ('241','La Quinta');
INSERT INTO localidad (id_localidad,nombre) values ('242','La Ramada');
INSERT INTO localidad (id_localidad,nombre) values ('243','La Rancherita y Las Cascadas');
INSERT INTO localidad (id_localidad,nombre) values ('244','La Rinconada');
INSERT INTO localidad (id_localidad,nombre) values ('245','Las Acequias');
INSERT INTO localidad (id_localidad,nombre) values ('246','Las Albahacas');
INSERT INTO localidad (id_localidad,nombre) values ('247','Las Arrias');
INSERT INTO localidad (id_localidad,nombre) values ('248','Las Bajadas');
INSERT INTO localidad (id_localidad,nombre) values ('249','Las Caleras');
INSERT INTO localidad (id_localidad,nombre) values ('250','Las Calles');
INSERT INTO localidad (id_localidad,nombre) values ('251','Las Cañadas');
INSERT INTO localidad (id_localidad,nombre) values ('252','Las Chacras');
INSERT INTO localidad (id_localidad,nombre) values ('253','Las Corzuelas');
INSERT INTO localidad (id_localidad,nombre) values ('254','La Serranita');
INSERT INTO localidad (id_localidad,nombre) values ('255','Las Gramillas');
INSERT INTO localidad (id_localidad,nombre) values ('256','Las Higueras');
INSERT INTO localidad (id_localidad,nombre) values ('257','Las Isletillas');
INSERT INTO localidad (id_localidad,nombre) values ('258','Las Jarillas');
INSERT INTO localidad (id_localidad,nombre) values ('259','Las Junturas');
INSERT INTO localidad (id_localidad,nombre) values ('260','Las Mojarras');
INSERT INTO localidad (id_localidad,nombre) values ('261','Las Oscuras');
INSERT INTO localidad (id_localidad,nombre) values ('262','Las Palmas');
INSERT INTO localidad (id_localidad,nombre) values ('263','Las Peñas (Sud)');
INSERT INTO localidad (id_localidad,nombre) values ('264','Las Peñas');
INSERT INTO localidad (id_localidad,nombre) values ('265','Las Perdices');
INSERT INTO localidad (id_localidad,nombre) values ('266','Las Playas');
INSERT INTO localidad (id_localidad,nombre) values ('267','Las Rabonas');
INSERT INTO localidad (id_localidad,nombre) values ('268','Las Saladas');
INSERT INTO localidad (id_localidad,nombre) values ('269','Las Tapias');
INSERT INTO localidad (id_localidad,nombre) values ('270','Las Varas');
INSERT INTO localidad (id_localidad,nombre) values ('271','Las Varillas');
INSERT INTO localidad (id_localidad,nombre) values ('272','Las Vertientes');
INSERT INTO localidad (id_localidad,nombre) values ('273','La Tordilla');
INSERT INTO localidad (id_localidad,nombre) values ('274','La Travesía');
INSERT INTO localidad (id_localidad,nombre) values ('275','Leguizamón');
INSERT INTO localidad (id_localidad,nombre) values ('276','Leones');
INSERT INTO localidad (id_localidad,nombre) values ('277','Loma Bola');
INSERT INTO localidad (id_localidad,nombre) values ('278','Los Callejones');
INSERT INTO localidad (id_localidad,nombre) values ('279','Los Cedros');
INSERT INTO localidad (id_localidad,nombre) values ('280','Los Cerrillos');
INSERT INTO localidad (id_localidad,nombre) values ('281','Los Chañaritos');
INSERT INTO localidad (id_localidad,nombre) values ('282','Los Chañaritos');
INSERT INTO localidad (id_localidad,nombre) values ('283','Los Cisnes');
INSERT INTO localidad (id_localidad,nombre) values ('284','Los Cocos');
INSERT INTO localidad (id_localidad,nombre) values ('285','Los Cóndores');
INSERT INTO localidad (id_localidad,nombre) values ('286','Los Hornillos');
INSERT INTO localidad (id_localidad,nombre) values ('287','Los Hoyos');
INSERT INTO localidad (id_localidad,nombre) values ('288','Los Mistoles');
INSERT INTO localidad (id_localidad,nombre) values ('289','Los Molinos');
INSERT INTO localidad (id_localidad,nombre) values ('290','Los Molles');
INSERT INTO localidad (id_localidad,nombre) values ('291','Los Molles');
INSERT INTO localidad (id_localidad,nombre) values ('292','Los Pozos');
INSERT INTO localidad (id_localidad,nombre) values ('293','Los Reartes');
INSERT INTO localidad (id_localidad,nombre) values ('294','Los Surgentes');
INSERT INTO localidad (id_localidad,nombre) values ('295','Los Talares');
INSERT INTO localidad (id_localidad,nombre) values ('296','Los Zorros');
INSERT INTO localidad (id_localidad,nombre) values ('297','Lozada');
INSERT INTO localidad (id_localidad,nombre) values ('298','Luca');
INSERT INTO localidad (id_localidad,nombre) values ('299','Lucio V. Mansilla');
INSERT INTO localidad (id_localidad,nombre) values ('300','Luque');
INSERT INTO localidad (id_localidad,nombre) values ('301','Lutti');
INSERT INTO localidad (id_localidad,nombre) values ('302','Luyaba');
INSERT INTO localidad (id_localidad,nombre) values ('303','Malagueño');
INSERT INTO localidad (id_localidad,nombre) values ('304','Malena');
INSERT INTO localidad (id_localidad,nombre) values ('305','Mallín');
INSERT INTO localidad (id_localidad,nombre) values ('306','Malvinas Argentinas');
INSERT INTO localidad (id_localidad,nombre) values ('307','Manfredi');
INSERT INTO localidad (id_localidad,nombre) values ('308','Maquinista Gallini');
INSERT INTO localidad (id_localidad,nombre) values ('309','Marcos Juárez');
INSERT INTO localidad (id_localidad,nombre) values ('310','Marull');
INSERT INTO localidad (id_localidad,nombre) values ('311','Matorrales');
INSERT INTO localidad (id_localidad,nombre) values ('312','Mattaldi');
INSERT INTO localidad (id_localidad,nombre) values ('313','Mayu Sumaj');
INSERT INTO localidad (id_localidad,nombre) values ('314','Media Naranja');
INSERT INTO localidad (id_localidad,nombre) values ('315','Melo');
INSERT INTO localidad (id_localidad,nombre) values ('316','Mendiolaza');
INSERT INTO localidad (id_localidad,nombre) values ('317','Mi Granja');
INSERT INTO localidad (id_localidad,nombre) values ('318','Mina Clavero');
INSERT INTO localidad (id_localidad,nombre) values ('319','Miramar');
INSERT INTO localidad (id_localidad,nombre) values ('320','Monte Buey');
INSERT INTO localidad (id_localidad,nombre) values ('321','Monte Cristo');
INSERT INTO localidad (id_localidad,nombre) values ('322','Monte de los Gauchos');
INSERT INTO localidad (id_localidad,nombre) values ('323','Monte del Rosario');
INSERT INTO localidad (id_localidad,nombre) values ('324','Monte Leña');
INSERT INTO localidad (id_localidad,nombre) values ('325','Monte Maíz');
INSERT INTO localidad (id_localidad,nombre) values ('326','Monte Ralo');
INSERT INTO localidad (id_localidad,nombre) values ('327','Morrison');
INSERT INTO localidad (id_localidad,nombre) values ('328','Morteros');
INSERT INTO localidad (id_localidad,nombre) values ('329','Mussi');
INSERT INTO localidad (id_localidad,nombre) values ('330','Nicolás Bruzzone');
INSERT INTO localidad (id_localidad,nombre) values ('331','Noetinger');
INSERT INTO localidad (id_localidad,nombre) values ('332','Nono');
INSERT INTO localidad (id_localidad,nombre) values ('333','Obispo Trejo');
INSERT INTO localidad (id_localidad,nombre) values ('334','Olaeta');
INSERT INTO localidad (id_localidad,nombre) values ('335','Oliva');
INSERT INTO localidad (id_localidad,nombre) values ('336','Olivares de San Nicolás');
INSERT INTO localidad (id_localidad,nombre) values ('337','Onagoity');
INSERT INTO localidad (id_localidad,nombre) values ('338','Oncativo');
INSERT INTO localidad (id_localidad,nombre) values ('339','Ordóñez');
INSERT INTO localidad (id_localidad,nombre) values ('340','Pacheco de Melo');
INSERT INTO localidad (id_localidad,nombre) values ('341','Pajas Blancas');
INSERT INTO localidad (id_localidad,nombre) values ('342','Pampayasta Norte');
INSERT INTO localidad (id_localidad,nombre) values ('343','Pampayasta Sur');
INSERT INTO localidad (id_localidad,nombre) values ('344','Panaholma');
INSERT INTO localidad (id_localidad,nombre) values ('345','Parque Calmayo');
INSERT INTO localidad (id_localidad,nombre) values ('346','Pascanas');
INSERT INTO localidad (id_localidad,nombre) values ('347','Pasco');
INSERT INTO localidad (id_localidad,nombre) values ('348','Paso del Durazno');
INSERT INTO localidad (id_localidad,nombre) values ('349','Paso del Durazno');
INSERT INTO localidad (id_localidad,nombre) values ('350','Paso Viejo');
INSERT INTO localidad (id_localidad,nombre) values ('351','Pilar');
INSERT INTO localidad (id_localidad,nombre) values ('352','Pincén');
INSERT INTO localidad (id_localidad,nombre) values ('353','Piquillín');
INSERT INTO localidad (id_localidad,nombre) values ('354','Plaza de Mercedes');
INSERT INTO localidad (id_localidad,nombre) values ('355','Plaza Luxardo');
INSERT INTO localidad (id_localidad,nombre) values ('356','Plaza San Francisco');
INSERT INTO localidad (id_localidad,nombre) values ('357','Porteña');
INSERT INTO localidad (id_localidad,nombre) values ('358','Potrero de Garay');
INSERT INTO localidad (id_localidad,nombre) values ('359','Pozo del Molle');
INSERT INTO localidad (id_localidad,nombre) values ('360','Pozo Nuevo');
INSERT INTO localidad (id_localidad,nombre) values ('361','Pueblo Comechingones');
INSERT INTO localidad (id_localidad,nombre) values ('362','Pueblo Italiano');
INSERT INTO localidad (id_localidad,nombre) values ('363','Puesto de Castro');
INSERT INTO localidad (id_localidad,nombre) values ('364','Punta del Agua');
INSERT INTO localidad (id_localidad,nombre) values ('365','Quebracho Herrado');
INSERT INTO localidad (id_localidad,nombre) values ('366','Quebracho Ladeado');
INSERT INTO localidad (id_localidad,nombre) values ('367','Quebrada de los Pozos');
INSERT INTO localidad (id_localidad,nombre) values ('368','Quebrada de Luna');
INSERT INTO localidad (id_localidad,nombre) values ('369','Quilino');
INSERT INTO localidad (id_localidad,nombre) values ('370','Rafael García');
INSERT INTO localidad (id_localidad,nombre) values ('371','Ramón J. Cárcano');
INSERT INTO localidad (id_localidad,nombre) values ('372','Ranqueles');
INSERT INTO localidad (id_localidad,nombre) values ('373','Rayo Cortado');
INSERT INTO localidad (id_localidad,nombre) values ('374','Rincón');
INSERT INTO localidad (id_localidad,nombre) values ('375','Río Bamba');
INSERT INTO localidad (id_localidad,nombre) values ('376','Río Ceballos');
INSERT INTO localidad (id_localidad,nombre) values ('377','Río Cuarto');
INSERT INTO localidad (id_localidad,nombre) values ('378','Río de los Sauces');
INSERT INTO localidad (id_localidad,nombre) values ('379','Río Primero');
INSERT INTO localidad (id_localidad,nombre) values ('380','Río Segundo');
INSERT INTO localidad (id_localidad,nombre) values ('381','Río Tercero');
INSERT INTO localidad (id_localidad,nombre) values ('382','Rosales');
INSERT INTO localidad (id_localidad,nombre) values ('383','Rosario del Saladillo');
INSERT INTO localidad (id_localidad,nombre) values ('384','Sacanta');
INSERT INTO localidad (id_localidad,nombre) values ('385','Sagrada Familia');
INSERT INTO localidad (id_localidad,nombre) values ('386','Saira');
INSERT INTO localidad (id_localidad,nombre) values ('387','Saladillo');
INSERT INTO localidad (id_localidad,nombre) values ('388','Saldán');
INSERT INTO localidad (id_localidad,nombre) values ('389','Salsacate');
INSERT INTO localidad (id_localidad,nombre) values ('390','Salsipuedes');
INSERT INTO localidad (id_localidad,nombre) values ('391','Sampacho');
INSERT INTO localidad (id_localidad,nombre) values ('392','Sanabria');
INSERT INTO localidad (id_localidad,nombre) values ('393','San Agustín');
INSERT INTO localidad (id_localidad,nombre) values ('394','San Antonio de Arredondo');
INSERT INTO localidad (id_localidad,nombre) values ('395','San Antonio de Litín');
INSERT INTO localidad (id_localidad,nombre) values ('396','San Basilio');
INSERT INTO localidad (id_localidad,nombre) values ('397','San Carlos Minas');
INSERT INTO localidad (id_localidad,nombre) values ('398','San Clemente');
INSERT INTO localidad (id_localidad,nombre) values ('399','San Esteban');
INSERT INTO localidad (id_localidad,nombre) values ('400','San Francisco');
INSERT INTO localidad (id_localidad,nombre) values ('401','San Francisco del Chañar');
INSERT INTO localidad (id_localidad,nombre) values ('402','San Gerónimo');
INSERT INTO localidad (id_localidad,nombre) values ('403','San Huberto');
INSERT INTO localidad (id_localidad,nombre) values ('404','San Ignacio (Loteo San Javier)');
INSERT INTO localidad (id_localidad,nombre) values ('405','San Javier y Yacanto');
INSERT INTO localidad (id_localidad,nombre) values ('406','San Joaquín');
INSERT INTO localidad (id_localidad,nombre) values ('407','San José');
INSERT INTO localidad (id_localidad,nombre) values ('408','San José de la Dormida');
INSERT INTO localidad (id_localidad,nombre) values ('409','San José de las Salinas');
INSERT INTO localidad (id_localidad,nombre) values ('410','San Lorenzo');
INSERT INTO localidad (id_localidad,nombre) values ('411','San Marcos');
INSERT INTO localidad (id_localidad,nombre) values ('412','San Marcos Sierra');
INSERT INTO localidad (id_localidad,nombre) values ('413','San Martín');
INSERT INTO localidad (id_localidad,nombre) values ('414','San Nicolás ( - Tierra Alta)');
INSERT INTO localidad (id_localidad,nombre) values ('415','San Pedro');
INSERT INTO localidad (id_localidad,nombre) values ('416','San Pedro de Gütemberg');
INSERT INTO localidad (id_localidad,nombre) values ('417','San Pedro de Toyos');
INSERT INTO localidad (id_localidad,nombre) values ('418','San Pedro Norte');
INSERT INTO localidad (id_localidad,nombre) values ('419','San Roque');
INSERT INTO localidad (id_localidad,nombre) values ('420','San Severo');
INSERT INTO localidad (id_localidad,nombre) values ('421','Santa Catalina (Holmberg)');
INSERT INTO localidad (id_localidad,nombre) values ('422','Santa Catalina');
INSERT INTO localidad (id_localidad,nombre) values ('423','Santa Elena');
INSERT INTO localidad (id_localidad,nombre) values ('424','Santa Elena');
INSERT INTO localidad (id_localidad,nombre) values ('425','Santa Eufemia');
INSERT INTO localidad (id_localidad,nombre) values ('426','Santa Magdalena (Est. Jovita)');
INSERT INTO localidad (id_localidad,nombre) values ('427','Santa María de Punilla');
INSERT INTO localidad (id_localidad,nombre) values ('428','Santa Rosa de Calamuchita');
INSERT INTO localidad (id_localidad,nombre) values ('429','Santa Rosa de Río Primero');
INSERT INTO localidad (id_localidad,nombre) values ('430','Santiago Temple');
INSERT INTO localidad (id_localidad,nombre) values ('431','San Vicente');
INSERT INTO localidad (id_localidad,nombre) values ('432','Sarmiento');
INSERT INTO localidad (id_localidad,nombre) values ('433','Saturnino María Laspiur');
INSERT INTO localidad (id_localidad,nombre) values ('434','Sauce Arriba');
INSERT INTO localidad (id_localidad,nombre) values ('435','Sebastián Elcano');
INSERT INTO localidad (id_localidad,nombre) values ('436','Seeber');
INSERT INTO localidad (id_localidad,nombre) values ('437','Segunda Usina');
INSERT INTO localidad (id_localidad,nombre) values ('438','Serrano');
INSERT INTO localidad (id_localidad,nombre) values ('439','Serrezuela');
INSERT INTO localidad (id_localidad,nombre) values ('440','Silvio Pellico');
INSERT INTO localidad (id_localidad,nombre) values ('441','Simbolar');
INSERT INTO localidad (id_localidad,nombre) values ('442','Sinsacate');
INSERT INTO localidad (id_localidad,nombre) values ('443','Socavones');
INSERT INTO localidad (id_localidad,nombre) values ('444','Solar de los Molinos');
INSERT INTO localidad (id_localidad,nombre) values ('445','Suco');
INSERT INTO localidad (id_localidad,nombre) values ('446','Tala Cañada');
INSERT INTO localidad (id_localidad,nombre) values ('447','Tala Huasi');
INSERT INTO localidad (id_localidad,nombre) values ('448','Talaini');
INSERT INTO localidad (id_localidad,nombre) values ('449','Tancacha');
INSERT INTO localidad (id_localidad,nombre) values ('450','Taninga');
INSERT INTO localidad (id_localidad,nombre) values ('451','Tanti');
INSERT INTO localidad (id_localidad,nombre) values ('452','Tasna');
INSERT INTO localidad (id_localidad,nombre) values ('453','Ticino');
INSERT INTO localidad (id_localidad,nombre) values ('454','Tinoco');
INSERT INTO localidad (id_localidad,nombre) values ('455','Tío Pujio');
INSERT INTO localidad (id_localidad,nombre) values ('456','Toledo');
INSERT INTO localidad (id_localidad,nombre) values ('457','Toro Pujio');
INSERT INTO localidad (id_localidad,nombre) values ('458','Tosno');
INSERT INTO localidad (id_localidad,nombre) values ('459','Tosquitas');
INSERT INTO localidad (id_localidad,nombre) values ('460','Tránsito');
INSERT INTO localidad (id_localidad,nombre) values ('461','Tuclame');
INSERT INTO localidad (id_localidad,nombre) values ('462','Ucacha');
INSERT INTO localidad (id_localidad,nombre) values ('463','Unquillo');
INSERT INTO localidad (id_localidad,nombre) values ('464','Valle Alegre');
INSERT INTO localidad (id_localidad,nombre) values ('465','Valle de Anisacate');
INSERT INTO localidad (id_localidad,nombre) values ('466','Valle Hermoso');
INSERT INTO localidad (id_localidad,nombre) values ('467','Viamonte');
INSERT INTO localidad (id_localidad,nombre) values ('468','Vicuña Mackenna');
INSERT INTO localidad (id_localidad,nombre) values ('469','Villa Albertina');
INSERT INTO localidad (id_localidad,nombre) values ('470','Villa Allende');
INSERT INTO localidad (id_localidad,nombre) values ('471','Villa Alpina');
INSERT INTO localidad (id_localidad,nombre) values ('472','Villa Amancay');
INSERT INTO localidad (id_localidad,nombre) values ('473','Villa Ascasubi');
INSERT INTO localidad (id_localidad,nombre) values ('474','Villa Berna');
INSERT INTO localidad (id_localidad,nombre) values ('475','Villa Candelaria');
INSERT INTO localidad (id_localidad,nombre) values ('476','Villa Carlos Paz');
INSERT INTO localidad (id_localidad,nombre) values ('477','Villa Cerro Azul');
INSERT INTO localidad (id_localidad,nombre) values ('478','Villa Ciudad de América (Loteo Diego de Rojas)');
INSERT INTO localidad (id_localidad,nombre) values ('479','Villa Ciudad Parque Los Reartes');
INSERT INTO localidad (id_localidad,nombre) values ('480','Villa Concepción del Tío');
INSERT INTO localidad (id_localidad,nombre) values ('481','Villa Corazon de Maria');
INSERT INTO localidad (id_localidad,nombre) values ('482','Villa Cura Brochero');
INSERT INTO localidad (id_localidad,nombre) values ('483','Villa de las Rosas');
INSERT INTO localidad (id_localidad,nombre) values ('484','Villa del Dique');
INSERT INTO localidad (id_localidad,nombre) values ('485','Villa del Prado');
INSERT INTO localidad (id_localidad,nombre) values ('486','Villa del Rosario');
INSERT INTO localidad (id_localidad,nombre) values ('487','Villa del Totoral');
INSERT INTO localidad (id_localidad,nombre) values ('488','Villa del Tránsito');
INSERT INTO localidad (id_localidad,nombre) values ('489','Villa de María');
INSERT INTO localidad (id_localidad,nombre) values ('490','Villa de Pocho');
INSERT INTO localidad (id_localidad,nombre) values ('491','Villa de Soto');
INSERT INTO localidad (id_localidad,nombre) values ('492','Villa Dolores');
INSERT INTO localidad (id_localidad,nombre) values ('493','Villa El Chacay');
INSERT INTO localidad (id_localidad,nombre) values ('494','Villa El Fachinal ( - Parque Norte - Guiñazú Norte)');
INSERT INTO localidad (id_localidad,nombre) values ('495','Villa Elisa');
INSERT INTO localidad (id_localidad,nombre) values ('496','Villa El Tala');
INSERT INTO localidad (id_localidad,nombre) values ('497','Villa Flor Serrana');
INSERT INTO localidad (id_localidad,nombre) values ('498','Villa Fontana');
INSERT INTO localidad (id_localidad,nombre) values ('499','Villa General Belgrano');
INSERT INTO localidad (id_localidad,nombre) values ('500','Villa Giardino');
INSERT INTO localidad (id_localidad,nombre) values ('501','Villa Gutiérrez');
INSERT INTO localidad (id_localidad,nombre) values ('502','Villa Huidobro');
INSERT INTO localidad (id_localidad,nombre) values ('503','Villa La Bolsa');
INSERT INTO localidad (id_localidad,nombre) values ('504','Villa Lago Azul');
INSERT INTO localidad (id_localidad,nombre) values ('505','Villa La Rivera');
INSERT INTO localidad (id_localidad,nombre) values ('506','Villa La Viña');
INSERT INTO localidad (id_localidad,nombre) values ('507','Villa Los Aromos');
INSERT INTO localidad (id_localidad,nombre) values ('508','Villa Los Llanos ( - Juárez Celman)');
INSERT INTO localidad (id_localidad,nombre) values ('509','Villa Los Patos');
INSERT INTO localidad (id_localidad,nombre) values ('510','Villa María');
INSERT INTO localidad (id_localidad,nombre) values ('511','Villa Nueva');
INSERT INTO localidad (id_localidad,nombre) values ('512','Villa Oeste');
INSERT INTO localidad (id_localidad,nombre) values ('513','Villa Parque Santa Ana');
INSERT INTO localidad (id_localidad,nombre) values ('514','Villa Parque Siquimán');
INSERT INTO localidad (id_localidad,nombre) values ('515','Villa Quilino');
INSERT INTO localidad (id_localidad,nombre) values ('516','Villa Quillinzo');
INSERT INTO localidad (id_localidad,nombre) values ('517','Villa Reducción');
INSERT INTO localidad (id_localidad,nombre) values ('518','Villa Río Icho Cruz');
INSERT INTO localidad (id_localidad,nombre) values ('519','Villa Rossi');
INSERT INTO localidad (id_localidad,nombre) values ('520','Villa Rumipal');
INSERT INTO localidad (id_localidad,nombre) values ('521','Villa San Esteban');
INSERT INTO localidad (id_localidad,nombre) values ('522','Villa San Isidro');
INSERT INTO localidad (id_localidad,nombre) values ('523','Villa San José');
INSERT INTO localidad (id_localidad,nombre) values ('524','Villa Santa Cruz del Lago');
INSERT INTO localidad (id_localidad,nombre) values ('525','Villa Santa Eugenia');
INSERT INTO localidad (id_localidad,nombre) values ('526','Villa Sarmiento');
INSERT INTO localidad (id_localidad,nombre) values ('527','Villa Sarmiento');
INSERT INTO localidad (id_localidad,nombre) values ('528','Villa Sierras de Oro');
INSERT INTO localidad (id_localidad,nombre) values ('529','Villa Tulumba');
INSERT INTO localidad (id_localidad,nombre) values ('530','Villa Valeria');
INSERT INTO localidad (id_localidad,nombre) values ('531','Villa Yacanto (Yacanto de Calamuchita)');
INSERT INTO localidad (id_localidad,nombre) values ('532','Washington');
INSERT INTO localidad (id_localidad,nombre) values ('533','Wenceslao Escalante');
INSERT INTO localidad (id_localidad,nombre) values ('534','Yocsina');

update cliente set id_localidad = '190' where id_localidad = '1';
delete from localidad where id_localidad = '1';

update cliente set id_localidad = '139' where id_localidad = '2';
delete from localidad where id_localidad = '2';

update cliente set id_localidad = '35' where id_localidad = '3';
delete from localidad where id_localidad = '3';

update cliente set id_localidad = '510' where id_localidad = '4';
delete from localidad where id_localidad = '4';

update cliente set id_localidad = '181' where id_localidad = '5';
delete from localidad where id_localidad = '5';

update cliente set id_localidad = '180' where id_localidad = '6';
delete from localidad where id_localidad = '6';

update cliente set id_localidad = '335' where id_localidad = '7';
delete from localidad where id_localidad = '7';

update cliente set id_localidad = '338' where id_localidad = '8';
delete from localidad where id_localidad = '8';

update cliente set id_localidad = '449' where id_localidad = '9';
delete from localidad where id_localidad = '9';

update cliente set id_localidad = '182' where id_localidad = '10';
delete from localidad where id_localidad = '10';

update cliente set id_localidad = '381' where id_localidad = '11';
delete from localidad where id_localidad = '11';

update cliente set id_localidad = '22' where id_localidad = '12';
delete from localidad where id_localidad = '12';

update cliente set id_localidad = '124' where id_localidad = '13';
delete from localidad where id_localidad = '13';

DROP TABLE pedido_estado;
CREATE TABLE pedido_estado
(
  id_pedido_estado serial NOT NULL,
  nombre character varying(128) NOT NULL,
  descripcion character varying(256),
  CONSTRAINT pedido_estado_pkey PRIMARY KEY (id_pedido_estado)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE pedido_estado OWNER TO postgres;

insert into pedido_estado (id_pedido_estado, nombre) values (1,'NUEVO');
insert into pedido_estado (id_pedido_estado, nombre) values (2,'PENDIENTE ENTREGA');
insert into pedido_estado (id_pedido_estado, nombre) values (3,'ENTREGADO PARCIAL');
insert into pedido_estado (id_pedido_estado, nombre) values (4,'ENTREGADO');
insert into pedido_estado (id_pedido_estado, nombre) values (5,'CANCELADO');

ALTER TABLE pedido ADD column id_pedido_estado integer NOT NULL default 1;
ALTER TABLE pedido ADD CONSTRAINT pedido_fk_2 FOREIGN KEY (id_pedido_estado)
      REFERENCES pedido_estado (id_pedido_estado) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;
	  
ALTER TABLE producto RENAME cantidad TO medida;
ALTER TABLE detalle_presupuesto ADD COLUMN medida double precision NOT NULL DEFAULT 1;
ALTER TABLE detalle_pedido ADD COLUMN medida double precision NOT NULL DEFAULT 1;

update detalle_pedido set medida = cantidad;
update detalle_pedido set cantidad = 1;

update detalle_presupuesto set medida = cantidad;
update detalle_presupuesto set cantidad = 1;