package com.ceriarte.central.dominio;

// Generated 11-sep-2013 16:52:16 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Caja generated by hbm2java
 */
@Entity
@Table(name = "caja", schema = "public")
public class Caja implements java.io.Serializable {

	private static final long serialVersionUID = 1463053559582644649L;

	private int idCaja;
	private Usuario usuario;
	private Date fechaHoraApertura;
	private Date fechaHoraCierre;
	private Set<MovimientoCaja> movimientoCajas = new HashSet<MovimientoCaja>(0);

	public Caja() {
	}

	public Caja(int idCaja, Usuario usuario, Date fechaHoraApertura) {
		this.idCaja = idCaja;
		this.usuario = usuario;
		this.fechaHoraApertura = fechaHoraApertura;
	}

	public Caja(Usuario usuario, Date fechaHoraApertura) {
		this.usuario = usuario;
		this.fechaHoraApertura = fechaHoraApertura;
	}

	public Caja(int idCaja, Usuario usuario, Date fechaHoraApertura,
			Date fechaHoraCierre, Set<MovimientoCaja> movimientoCajas) {
		this.idCaja = idCaja;
		this.usuario = usuario;
		this.fechaHoraApertura = fechaHoraApertura;
		this.fechaHoraCierre = fechaHoraCierre;
		this.movimientoCajas = movimientoCajas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_caja", unique = true, nullable = false)
	public int getIdCaja() {
		return this.idCaja;
	}

	public void setIdCaja(int idCaja) {
		this.idCaja = idCaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora_apertura", nullable = false, length = 29)
	public Date getFechaHoraApertura() {
		return this.fechaHoraApertura;
	}

	public void setFechaHoraApertura(Date fechaHoraApertura) {
		this.fechaHoraApertura = fechaHoraApertura;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora_cierre", length = 29)
	public Date getFechaHoraCierre() {
		return this.fechaHoraCierre;
	}

	public void setFechaHoraCierre(Date fechaHoraCierre) {
		this.fechaHoraCierre = fechaHoraCierre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caja", cascade = { CascadeType.MERGE })
	public Set<MovimientoCaja> getMovimientoCajas() {
		return this.movimientoCajas;
	}

	public void setMovimientoCajas(Set<MovimientoCaja> movimientoCajas) {
		this.movimientoCajas = movimientoCajas;
	}

}
