package com.ceriarte.central.dominio;

// Generated 11-sep-2013 18:19:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClienteEstado generated by hbm2java
 */
@Entity
@Table(name = "cliente_estado", schema = "public")
public class ClienteEstado implements java.io.Serializable {

	private static final long serialVersionUID = -3152441633760879427L;
	
	private String idClienteEstado;
	private String nombre;
	private String descripcion;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public ClienteEstado() {
	}
	
	public ClienteEstado(String idClienteEstado) {
		this.idClienteEstado = idClienteEstado;
	}

	public ClienteEstado(String idClienteEstado, String nombre) {
		this.idClienteEstado = idClienteEstado;
		this.nombre = nombre;
	}

	public ClienteEstado(String idClienteEstado, String nombre,
			String descripcion, Set<Cliente> clientes) {
		this.idClienteEstado = idClienteEstado;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.clientes = clientes;
	}

	@Id
	@Column(name = "id_cliente_estado", unique = true, nullable = false, length = 3)
	public String getIdClienteEstado() {
		return this.idClienteEstado;
	}

	public void setIdClienteEstado(String idClienteEstado) {
		this.idClienteEstado = idClienteEstado;
	}

	@Column(name = "nombre", nullable = false, length = 128)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 256)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clienteEstado")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
