package com.ceriarte.central.dominio;

// Generated 11-sep-2013 18:19:09 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Cliente implements java.io.Serializable {

	private static final long serialVersionUID = 4559111428579103149L;

	private int idCliente;
	private ClienteEstado clienteEstado;
	private String nombre;
	private String apellido;
	private String email;
	private String domicilio;
	private Localidad localidad;
	private String telefono;
	private Date fechaCreacion;
	private ResponsabilidadIVA responsabilidadIVA;
	private String cuit;
	private boolean borrado;
	
	public Cliente() {
	}

	public Cliente(ClienteEstado clienteEstado, String nombre, String apellido,
				   String email, String domicilio, Localidad localidad, String telefono, String cuit, ResponsabilidadIVA responsabilidadIVA) {
		this.clienteEstado = clienteEstado;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.domicilio = domicilio;
		this.localidad = localidad;
		this.telefono = telefono;
		this.cuit = cuit;
		this.responsabilidadIVA = responsabilidadIVA;
		this.fechaCreacion = new Date();
	}


	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_cliente", unique = true, nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente_estado", nullable = false)
	public ClienteEstado getClienteEstado() {
		return this.clienteEstado;
	}

	public void setClienteEstado(ClienteEstado clienteEstado) {
		this.clienteEstado = clienteEstado;
	}

	@Column(name = "nombre", nullable = false, length = 128)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false, length = 128)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "email", unique = true, length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "domicilio", length = 256)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_localidad")
	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	@Column(name = "telefono", length = 128)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_responsabilidad_iva")
	public ResponsabilidadIVA getResponsabilidadIVA() {
		return responsabilidadIVA;
	}

	public void setResponsabilidadIVA(ResponsabilidadIVA responsabilidadIVA) {
		this.responsabilidadIVA = responsabilidadIVA;
	}

	@Column(name = "cuit")
	public String getCuit() {
		return cuit;
	}

	public void setCuit(String cuit) {
		this.cuit = cuit;
	}

	@Column(name = "borrado")
	public boolean isBorrado() {
		return borrado;
	}

	public void setBorrado(boolean borrado) {
		this.borrado = borrado;
	}
	
	@Transient
	public String getNombreCompleto() {
		return this.nombre + " " + this.apellido;
	}
}
