package com.ceriarte.central.dominio;

// Generated 11-sep-2013 18:19:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MedioDePago generated by hbm2java
 */
@Entity
@Table(name = "medio_de_pago", schema = "public")
public class MedioDePago implements java.io.Serializable {

	private static final long serialVersionUID = -4880695276079130555L;

	private int idMedioDePago;
	private String descripcion;
	private String abreviatura;
	private boolean habilitado;

	public MedioDePago() {
	}

	public MedioDePago(int idMedioDePago) {
		this.idMedioDePago = idMedioDePago;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_medio_de_pago", unique = true, nullable = false)
	public int getIdMedioDePago() {
		return this.idMedioDePago;
	}

	public void setIdMedioDePago(int idMedioDePago) {
		this.idMedioDePago = idMedioDePago;
	}

	@Column(name = "descripcion", length = 256)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "abreviatura", length = 3)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

}
