package com.ceriarte.central.dominio;

// Generated 11-sep-2013 18:19:09 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimientoCaja generated by hbm2java
 */
@Entity
@Table(name = "movimiento_caja", schema = "public")
public class MovimientoCaja implements java.io.Serializable {

	private static final long serialVersionUID = -435599598943351799L;
	
	private int idMovimientoCaja;
	private Caja caja;
	private Usuario usuario;
	private TipoMovimientoCaja tipoMovimientoCaja;
	private Date fechaHora;
	private Pedido pedido;
	private MedioDePago medioDePago;
	private double monto;

	
	public MovimientoCaja() {
	}

	public MovimientoCaja(int idMovimientoCaja, Caja caja, Usuario usuario,
			TipoMovimientoCaja tipoMovimientoCaja, Date fechaHora) {
		this.idMovimientoCaja = idMovimientoCaja;
		this.caja = caja;
		this.usuario = usuario;
		this.tipoMovimientoCaja = tipoMovimientoCaja;
		this.fechaHora = fechaHora;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_movimiento_caja", unique = true, nullable = false)
	public int getIdMovimientoCaja() {
		return this.idMovimientoCaja;
	}

	public void setIdMovimientoCaja(int idMovimientoCaja) {
		this.idMovimientoCaja = idMovimientoCaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_caja", nullable = false)
	public Caja getCaja() {
		return this.caja;
	}

	public void setCaja(Caja caja) {
		this.caja = caja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_movimiento_caja", nullable = false)
	public TipoMovimientoCaja getTipoMovimientoCaja() {
		return this.tipoMovimientoCaja;
	}

	public void setTipoMovimientoCaja(TipoMovimientoCaja tipoMovimientoCaja) {
		this.tipoMovimientoCaja = tipoMovimientoCaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora", nullable = false, length = 29)
	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pedido")
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_medio_de_pago")
	public MedioDePago getMedioDePago() {
		return medioDePago;
	}

	public void setMedioDePago(MedioDePago medioDePago) {
		this.medioDePago = medioDePago;
	}

	@Column(name = "monto", nullable = false)
	public double getMonto() {
		return monto;
	}

	public void setMonto(double monto) {
		this.monto = monto;
	}


}
