package com.ceriarte.central.dominio;

// Generated 11-sep-2013 18:19:09 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "orden_trabajo", schema = "public")
public class OrdenTrabajo implements java.io.Serializable {

	private static final long serialVersionUID = 8987926604915419724L;

	private int idOrdenTrabajo;
	private Usuario creadaPor;
	private Usuario asignadaA;
	private OrdenTrabajoEstado ordenTrabajoEstado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Date fechaEstimadaFin;
	private Set<DetalleOrdenTrabajo> detalles;
	private boolean borrado;
	private DetallePedido detallePedido;

	public OrdenTrabajo() {
	}

	public OrdenTrabajo(Usuario creadaPor, Usuario asignadaA, OrdenTrabajoEstado ordenTrabajoEstado, DetallePedido detallePedido, Date fechaEstimadaFin) {
		super();
		this.creadaPor = creadaPor;
		this.asignadaA = asignadaA;
		this.fechaCreacion = new Date();
		this.detalles = new HashSet<DetalleOrdenTrabajo>();
		this.ordenTrabajoEstado = ordenTrabajoEstado;
		this.detallePedido = detallePedido;
		this.fechaEstimadaFin = fechaEstimadaFin;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id_orden_trabajo", unique = true, nullable = false)
	public int getIdOrdenTrabajo() {
		return idOrdenTrabajo;
	}

	public void setIdOrdenTrabajo(int idOrdenTrabajo) {
		this.idOrdenTrabajo = idOrdenTrabajo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_creacion", nullable = false)
	public Usuario getCreadaPor() {
		return creadaPor;
	}

	public void setCreadaPor(Usuario creadaPor) {
		this.creadaPor = creadaPor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_asignacion")
	public Usuario getAsignadaA() {
		return asignadaA;
	}

	public void setAsignadaA(Usuario asignadaA) {
		this.asignadaA = asignadaA;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_orden_trabajo_estado", nullable = false)
	public OrdenTrabajoEstado getOrdenTrabajoEstado() {
		return ordenTrabajoEstado;
	}

	public void setOrdenTrabajoEstado(OrdenTrabajoEstado ordenTrabajoEstado) {
		this.ordenTrabajoEstado = ordenTrabajoEstado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 29)
	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_estimada_fin", length = 29)
	public Date getFechaEstimadaFin() {
		return fechaEstimadaFin;
	}

	public void setFechaEstimadaFin(Date fechaEstimadaFin) {
		this.fechaEstimadaFin = fechaEstimadaFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ordenTrabajo", cascade = {CascadeType.ALL})
	public Set<DetalleOrdenTrabajo> getDetalles() {
		return detalles;
	}

	public void setDetalles(Set<DetalleOrdenTrabajo> detalles) {
		this.detalles = detalles;
	}

	@Column(name = "borrado")
	public boolean isBorrado() {
		return borrado;
	}

	public void setBorrado(boolean borrado) {
		this.borrado = borrado;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade = {CascadeType.ALL})
	@JoinColumn(name = "id_detalle_pedido", nullable = false)
	public DetallePedido getDetallePedido() {
		return detallePedido;
	}

	public void setDetallePedido(DetallePedido detallePedido) {
		this.detallePedido = detallePedido;
	}


}
