package com.ceriarte.central.dominio;

// Generated 11-sep-2013 18:19:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name = "permiso", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Permiso implements java.io.Serializable {

	private static final long serialVersionUID = 6122762045625410667L;
	private int idPermiso;
	private String nombre;
	private String descripcion;
	
	public Permiso() {
	}

	public Permiso(int idPermiso, String nombre) {
		this.idPermiso = idPermiso;
		this.nombre = nombre;
	}


	@Id
	@Column(name = "id_permiso", unique = true, nullable = false)
	public int getIdPermiso() {
		return this.idPermiso;
	}

	public void setIdPermiso(int idPermiso) {
		this.idPermiso = idPermiso;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false, length = 128)
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((nombre == null) ? 0 : nombre.hashCode());
		return result;
	}

	//MFC equals tendría q comparar id y nombre, sólo id, ó solo nombre? 
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Permiso)) {
			return false;
		}
		Permiso other = (Permiso) obj;
		if (nombre == null) {
			if (other.nombre != null) {
				return false;
			}
		} else if (!nombre.equals(other.nombre)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Permiso [id=" + idPermiso + ", nombre=" + nombre + "]";
	}

}
