package com.ceriarte.central.dominio;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoMovimientoCaja generated by hbm2java
 */
@Entity
@Table(name = "tipo_movimiento_caja", schema = "public")
public class TipoMovimientoCaja implements java.io.Serializable {

	private static final long serialVersionUID = -6782096585454770786L;

	private String idTipoMovimientoCaja;
	private String nombre;
	private String descripcion;

	public TipoMovimientoCaja() {
	}

	public TipoMovimientoCaja(String idTipoMovimientoCaja, String nombre) {
		this.idTipoMovimientoCaja = idTipoMovimientoCaja;
		this.nombre = nombre;
	}

	public TipoMovimientoCaja(String idTipoMovimientoCaja, String nombre,
			String descripcion) {
		this.idTipoMovimientoCaja = idTipoMovimientoCaja;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "id_tipo_movimiento_caja", unique = true, nullable = false, length = 3)
	public String getIdTipoMovimientoCaja() {
		return this.idTipoMovimientoCaja;
	}

	public void setIdTipoMovimientoCaja(String idTipoMovimientoCaja) {
		this.idTipoMovimientoCaja = idTipoMovimientoCaja;
	}

	@Column(name = "nombre", nullable = false, length = 128)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 256)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}
