package com.ceriarte.central.dominio;

// Generated 11-sep-2013 18:19:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoDocIdentidad generated by hbm2java
 */
@Entity
@Table(name = "tipo_doc_identidad", schema = "public")
public class TipoDocIdentidad implements java.io.Serializable {

	private static final long serialVersionUID = -6042460950336110070L;

	private String idTipoDocIdentidad;
	private String nombre;
	private String descripcion;
	
	public TipoDocIdentidad() {
	}

	public TipoDocIdentidad(String idTipoDocIdentidad) {
		this.idTipoDocIdentidad = idTipoDocIdentidad;
	}
	
	public TipoDocIdentidad(String idTipoDocIdentidad, String nombre) {
		this.idTipoDocIdentidad = idTipoDocIdentidad;
		this.nombre = nombre;
	}

	public TipoDocIdentidad(String idTipoDocIdentidad, String nombre,
			String descripcion) {
		this.idTipoDocIdentidad = idTipoDocIdentidad;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "id_tipo_doc_identidad", unique = true, nullable = false, length = 3)
	public String getIdTipoDocIdentidad() {
		return this.idTipoDocIdentidad;
	}

	public void setIdTipoDocIdentidad(String idTipoDocIdentidad) {
		this.idTipoDocIdentidad = idTipoDocIdentidad;
	}

	@Column(name = "nombre", nullable = false, length = 128)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 256)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}
