package com.ceriarte.central.dominio;

// Generated 11-sep-2013 18:19:09 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoValor generated by hbm2java
 */
@Entity
@Table(name = "tipo_valor", schema = "public")
public class TipoValor implements java.io.Serializable {

	private static final long serialVersionUID = 172451729239991084L;

	private int idTipoValor;
	private String nombre;
	
	public TipoValor() {
	}

	public TipoValor(int idTipoValor) {
		this.idTipoValor = idTipoValor;
	}
	
	public TipoValor(int idTipoValor, String nombre) {
		this.idTipoValor = idTipoValor;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "id_tipo_valor", unique = true, nullable = false)
	public int getIdTipoValor() {
		return this.idTipoValor;
	}

	public void setIdTipoValor(int idTipoValor) {
		this.idTipoValor = idTipoValor;
	}

	@Column(name = "nombre", nullable = false, length = 128)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
